apiVersion: apps/v1
kind: Deployment
metadata:
  name: abashiri
spec:
  template:
    spec:
      terminationGracePeriodSeconds: 25
      nodeSelector:
        cloud.google.com/gke-spot: "true"
      tolerations:
        - key: cloud.google.com/gke-spot
          operator: Equal
          value: "true"
          effect: NoSchedule
      containers:
        - name: abashiri
          imagePullPolicy: Always
          env:
            - name: ABASHIRI_AUTH_ROOT
              value: "gs://mappf-experiment-abashiri-control/auth/"
            - name: ABASHIRI_STATE_ROOT
              value: "gs://mappf-experiment-demo/"
            - name: ABASHIRI_JOURNAL_ROOT
              value: "gs://mappf-experiment-abashiri-journal/"
            - name: ABASHIRI_STYLE_CATALOG
              value: "gs://mappf-experiment-abashiri-control/catalog/current.json"
            - name: ABASHIRI_STYLE_REFRESH_ENDPOINTS
              value: "http://biei-internal:9090/_internal/refresh/style,http://ishikari-internal:9090/_internal/refresh/style"
            - name: ABASHIRI_OPERATIONAL_STATUS_ENDPOINTS
              value: "biei=http://biei-internal:9090/_internal/operations/v1/status,ishikari=http://ishikari-internal:9090/_internal/operations/v1/status"
