apiVersion: v1
kind: Service
metadata:
  name: ishikari
  labels:
    app: ishikari
spec:
  type: ClusterIP
  selector:
    app: ishikari
  ports:
    - name: http
      port: 8080
      targetPort: http
