apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: biei
spec:
  selector:
    matchLabels:
      app: biei
  endpoints:
    - port: internal
      path: /_internal/metrics
      interval: 30s
