substitutions:
  _IMAGE: asia-northeast1-docker.pkg.dev/mappf-experiment/ishikari/ishikari:dev
options:
  machineType: E2_HIGHCPU_8
  diskSizeGb: 30
timeout: 1800s
steps:
  - name: gcr.io/cloud-builders/docker
    env: [DOCKER_BUILDKIT=1]
    args: [build, -f, demo-deploy/Dockerfile, -t, "${_IMAGE}", .]
images: ["${_IMAGE}"]
